spring:
  application:
    name: user-api-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: prod
#    include: mail

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force: true
      force-response: true

logging:
  level:
    com.phcworld: debug
    org.springframework.security: debug
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

jwt:
  secret: spring-boot-security-test-secret-key-dev

kafka:
  broker:
    url: 127.0.0.1:9092
gateway:
  ip: 127.0.0.1
