spring:
  application:
    name: user-api-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#  profiles:
#    active: mysql
#    include: mail

server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force: true
      force-response: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

jwt:
  secret: c3ByaW5nLXNlY3VyaXR5LWp3dC1waGMtd29ybGQtc2VjcmV0LWtleQ==

kafka:
  broker:
    url: 127.0.0.1:9092
